CREATE TABLE `NotificationAlert` (
  `id` CHAR(36) NOT NULL,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `eventType` VARCHAR(64) NOT NULL,
  `severity` VARCHAR(16) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `metadata` JSON NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  `firstObservedAt` DATETIME(3) NOT NULL,
  `lastObservedAt` DATETIME(3) NOT NULL,
  `resolvedAt` DATETIME(3) NULL,
  `webhookDeliveredAt` DATETIME(3) NULL,
  `webhookLastAttemptAt` DATETIME(3) NULL,
  `webhookLastError` VARCHAR(1000) NULL,
  `emailDeliveredAt` DATETIME(3) NULL,
  `emailLastAttemptAt` DATETIME(3) NULL,
  `emailLastError` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `NotificationAlert_dedupeKey_key`(`dedupeKey`),
  INDEX `NotificationAlert_status_lastObservedAt_idx`(`status`, `lastObservedAt`),
  INDEX `NotificationAlert_eventType_status_idx`(`eventType`, `status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
